export const staticGalleryData = [
  { title: "Foto Bersama Pak Hugi", category: "foto-kelas", bg: "linear-gradient(135deg, #5C1414 0%, #8B3333 100%)" },
  { title: "Praktikum Biologi Sel", category: "kegiatan", bg: "linear-gradient(160deg, #3A0A0A 0%, #6B2020 60%, #C4973A 100%)" },
  { title: "Upacara 17 Agustus", category: "kegiatan", bg: "linear-gradient(110deg, #7A2020 0%, #4A0E0E 100%)" },
  { title: "Baksos: Cegah Stunting", category: "momen", bg: "linear-gradient(145deg, #C4973A 0%, #8B6020 50%, #5C1414 100%)" },
  { title: "Kimia: Asam Basa", category: "kegiatan", bg: "linear-gradient(125deg, #4A0E0E 30%, #7A3535 100%)" },
  { title: "makan siang di kantin", category: "momen", bg: "linear-gradient(155deg, #6B2020 0%, #C4973A 100%)" },
  { title: "Foto Kelas Pertama", category: "foto-kelas", bg: "linear-gradient(170deg, #3A0A0A 0%, #5C1414 50%, #8B4040 100%)" },
  { title: "Piket Bersih-Bersih", category: "kegiatan", bg: "linear-gradient(120deg, #8B4020 0%, #5C1414 100%)" },
  { title: "Ultah Dadakan Kelas", category: "momen", bg: "linear-gradient(140deg, #5C1414 0%, #C4973A 80%, #8B6020 100%)" },
  { title: "Kunjungan Lab IPA", category: "kegiatan", bg: "linear-gradient(165deg, #4A0E0E 0%, #6B3030 100%)" },
  { title: "Class Meeting Sengit", category: "momen", bg: "linear-gradient(130deg, #7A2020 0%, #4A0E0E 70%, #C4973A 100%)" },
  { title: "Foto Akhir Semester Ganjil", category: "foto-kelas", bg: "linear-gradient(150deg, #3A0A0A 0%, #8B3333 100%)" },
];

export const staticStudents = [
  { absen: '01', name: 'Abyan Dzaky Pratama', role: 'Ketua Kelas', quote: 'Memimpin dengan teladan, melayani dengan hati.' },
  { absen: '02', name: 'Adinda Putri Rahayu', role: 'Wakil Ketua', quote: 'Kesuksesan adalah hasil dari kerja keras dan doa.' },
  { absen: '03', name: 'Aghna Nur Fadhilah', role: 'Sekretaris 1', quote: 'Setiap goresan tinta adalah jejak sejarah masa depan.' },
  { absen: '04', name: 'Ahmad Fauzi', role: '', quote: 'Diam itu emas, tapi ilmu adalah cahaya.' },
  { absen: '05', name: 'Aisha Nuraini', role: 'Bendahara 1', quote: 'Ketelitian adalah kunci dari keteraturan.' },
  { absen: '06', name: 'Alya Salsabila', role: '', quote: 'Jadilah dirimu sendiri, versi terbaik setiap hari.' },
  { absen: '07', name: 'Ananda Rizki Putra', role: '', quote: 'Masa depan milik mereka yang percaya pada mimpi.' },
  { absen: '08', name: 'Annisa Farah Diba', role: 'Sekretaris 2', quote: 'Kerapihan mencerminkan kebersihan pikiran.' },
  { absen: '09', name: 'Arif Rahman Hakim', role: '' },
  { absen: '10', name: 'Aulia Rahma Sari', role: '' },
  { absen: '11', name: 'Bagas Dwi Santoso', role: '' },
  { absen: '12', name: 'Bella Putri Andini', role: '' },
  { absen: '13', name: 'Cahya Ramadhan', role: '' },
  { absen: '14', name: 'Daffa Bintang Nugraha', role: '' },
  { absen: '15', name: 'Dea Amelia Putri', role: 'Bendahara 2' },
  { absen: '16', name: 'Dendi Saputra', role: '' },
  { absen: '17', name: 'Dhia Azzahra', role: '' },
  { absen: '18', name: 'Dimas Eka Pratama', role: '' },
  { absen: '19', name: 'Elsa Febrianti', role: '' },
  { absen: '20', name: 'Fadhil Akbar Maulana', role: '' },
  { absen: '21', name: 'Fathia Nur Azizah', role: '' },
  { absen: '22', name: 'Fikri Ramadhan', role: '' },
  { absen: '23', name: 'Gilang Permana', role: '' },
  { absen: '24', name: 'Hafidz Maulana', role: '' },
  { absen: '25', name: 'Hana Nur Aisyah', role: '' },
  { absen: '26', name: 'Ilham Saputra', role: '' },
  { absen: '27', name: 'Indah Permata Sari', role: '' },
  { absen: '28', name: 'Jasmine Putri Utami', role: '' },
  { absen: '29', name: 'Kevin Andriansyah', role: '' },
  { absen: '30', name: 'Layla Salsabila Putri', role: '' },
  { absen: '31', name: 'M. Farhan Ramadhan', role: '' },
  { absen: '32', name: 'Nadira Aulia', role: '' },
  { absen: '33', name: 'Putri Ramadhani', role: '' },
  { absen: '34', name: 'Rafi Ardiansyah', role: '' },
  { absen: '35', name: 'Salsabila Zahra', role: '' },
  { absen: '36', name: 'Zahra Nur Fadillah', role: '' }
];
