export const staticGalleryData = [
  { title: "Foto Bersama Pak Hugi", category: "foto-kelas", bg: "linear-gradient(135deg, #5C1414 0%, #8B3333 100%)", images: [] },
  { title: "Praktikum Biologi Sel", category: "kegiatan", bg: "linear-gradient(160deg, #3A0A0A 0%, #6B2020 60%, #C4973A 100%)", images: [] },
  { title: "Upacara 17 Agustus", category: "kegiatan", bg: "linear-gradient(110deg, #7A2020 0%, #4A0E0E 100%)", images: [] },
  { title: "Baksos: Cegah Stunting", category: "momen", bg: "linear-gradient(145deg, #C4973A 0%, #8B6020 50%, #5C1414 100%)", images: [] },
  { title: "Kimia: Asam Basa", category: "kegiatan", bg: "linear-gradient(125deg, #4A0E0E 30%, #7A3535 100%)", images: [] },
  { title: "makan siang di kantin", category: "momen", bg: "linear-gradient(155deg, #6B2020 0%, #C4973A 100%)", images: [] },
  { title: "Foto Kelas Pertama", category: "foto-kelas", bg: "linear-gradient(170deg, #3A0A0A 0%, #5C1414 50%, #8B4040 100%)", images: [] },
  { title: "Piket Bersih-Bersih", category: "kegiatan", bg: "linear-gradient(120deg, #8B4020 0%, #5C1414 100%)", images: [] },
  { title: "Ultah Dadakan Kelas", category: "momen", bg: "linear-gradient(140deg, #5C1414 0%, #C4973A 80%, #8B6020 100%)", images: [] },
  { title: "Kunjungan Lab IPA", category: "kegiatan", bg: "linear-gradient(165deg, #4A0E0E 0%, #6B3030 100%)", images: [] },
  { title: "Class Meeting Sengit", category: "momen", bg: "linear-gradient(130deg, #7A2020 0%, #4A0E0E 70%, #C4973A 100%)", images: [] },
  { title: "Foto Akhir Semester Ganjil", category: "foto-kelas", bg: "linear-gradient(150deg, #3A0A0A 0%, #8B3333 100%)", images: [] },
];

export const staticStudents = [
  { absen: '01', name: 'Adam Mudzaki', role: 'Seksi Olahraga / Kesehatan', quote: 'Memimpin dengan ketegasan, menyatukan dengan kebersamaan XII IPA 5.' },
  { absen: '02', name: 'Aghna Fathi Putra Buono', role: '', quote: 'Setiap coretan tinta merekam perjalanan tak terlupakan kelas kita.' },
  { absen: '03', name: 'Alisha Putri Vallena Haris', role: 'Ketua Kelas', quote: 'Mendukung setiap langkah demi kebaikan dan keharmonisan kelas.' },
  { absen: '04', name: 'Asyifa Khoerunnisa', role: 'Seksi Upacara / Keamanan', quote: 'Jadilah dirimu sendiri, versi terbaik di setiap kesempatan.' },
  { absen: '05', name: 'Axelizar Achmad', role: 'Seksi Pendidikan', quote: 'Dalam tubuh yang sehat terdapat jiwa yang kuat.' },
  { absen: '06', name: 'Bagas Adiwitya Ramadhan', role: '', quote: 'Sportivitas dan kebersamaan adalah pondasi persaudaraan.' },
  { absen: '07', name: 'Chiara Alverina Lusia', role: '', quote: 'Kerapian catatan adalah cermin ketelitian fungsional kelas.' },
  { absen: '08', name: 'Christian Jhosua Halomoan Hutabarat', role: 'Seksi Kebersihan', quote: 'Kebersihan lingkungan belajar mencerminkan jernihnya pikiran.' },
  { absen: '09', name: 'Damai Prasasti Permata Rohaeno', role: '', quote: 'Kedisiplinan di setiap langkah membentuk masa depan gemilang.' },
  { absen: '10', name: 'Diandra Pravita Nurani', role: 'Sekretaris 1', quote: 'Transparansi keuangan kelas adalah amanah yang utama.' },
  { absen: '11', name: 'Dimas Alfarizky', role: 'Seksi Olahraga / Kesehatan', quote: 'Menjunjung keseragaman dan integritas di setiap kesempatan.' },
  { absen: '12', name: 'Elsa Widuri', role: '', quote: 'Mengelola anggaran dengan penuh integritas dan tanggung jawab.' },
  { absen: '13', name: 'Faradisa Putri Dwidianto', role: '', quote: 'Impian besar dimulai dari langkah-langkah kecil hari ini.' },
  { absen: '14', name: 'Ghina Ayundia Fairuz', role: 'Seksi Pendidikan', quote: 'Ilmu pengetahuan adalah pelita hidup menuju kesuksesan.' },
  { absen: '15', name: 'Hanzhalah Abdurrahman Al Fayyad', role: 'Seksi Peralatan', quote: 'Merawat kebersihan kelas demi kenyamanan bersama.' },
  { absen: '16', name: 'Intan Ayu Melani', role: '', quote: 'Senyuman hangat selalu bisa mencairkan suasana.' },
  { absen: '17', name: 'Jeconia Sally Viani', role: '', quote: 'Belajar tiada henti, berproses tiada henti.' },
  { absen: '18', name: 'Katriel Laquisha Hannah', role: '', quote: 'Kejujuran dan ketulusan hati adalah bekal terbaik hidup.' },
  { absen: '19', name: 'Keisha Kaila Harmanto', role: '', quote: 'Menari mengikuti ritme kehidupan dengan penuh percaya diri.' },
  { absen: '20', name: 'Kevin Caresto Gisellas', role: '', quote: 'Fokus pada tujuan, lintasi tantangan dengan kecerdasan.' },
  { absen: '21', name: 'Maura Esther Tiara Hartana', role: 'Seksi Kebersihan', quote: 'Kreativitas tanpa batas melahirkan keunikan diri.' },
  { absen: '22', name: 'Muhammad Vicky Wiraputra', role: 'Seksi Peralatan', quote: 'Keberanian untuk mencoba adalah awal dari keberhasilan.' },
  { absen: '23', name: 'Nabillah Nuraini Kurniawan', role: '', quote: 'Tebar kebaikan kapan saja dan di mana saja.' },
  { absen: '24', name: 'Nadien Karlina Putri', role: '', quote: 'Sinar mentari selalu hadir setelah gelap malam usai.' },
  { absen: '25', name: 'Nafisha Putri Radisty', role: 'Seksi Kerohanian', quote: 'Keindahan sejati memancar dari ketulusan hati.' },
  { absen: '26', name: 'Naysila Zahrah Vandiliana', role: '', quote: 'Belajar dari masa lalu, melangkah mantap ke masa depan.' },
  { absen: '27', name: 'Nova Ariyanti', role: '', quote: 'Setiap tantangan adalah peluang untuk tumbuh dewasa.' },
  { absen: '28', name: 'Novailla Salwa Khoirunisa', role: 'Bendahara 1', quote: 'Kedamaian hati bersumber dari rasa syukur kita.' },
  { absen: '29', name: 'Octaviana Sintya Mardiyanti', role: 'Wakil Ketua', quote: 'Teruslah bersinar dengan caramu sendiri.' },
  { absen: '30', name: 'Rafah Dhita Syalma', role: '', quote: 'Ketekunan adalah kunci pembuka pintu impian.' },
  { absen: '31', name: 'Raffiendra Ghazan Ari Nugroho', role: 'Seksi Upacara / Keamanan', quote: 'Kecerdasan tanpa kompas moral bagaikan kapal tanpa kemudi.' },
  { absen: '32', name: 'Rasendriya Bhamakerti', role: 'Seksi Kerohanian', quote: 'Keharmonisan kelas terwujud lewat saling menghargai.' },
  { absen: '33', name: 'Regina Caecilia Wahyuni', role: '', quote: 'Musik kehidupan terdengar indah jika kita mensyukurinya.' },
  { absen: '34', name: 'Salma Tazkiyyatul Aqwal', role: 'Bendahara 2', quote: 'Kata-kata yang bijak mencerminkan jiwa yang tenang.' },
  { absen: '35', name: 'Yulia Sari', role: '', quote: 'Persahabatan sejati tak lekang oleh waktu dan jarak.' },
  { absen: '36', name: 'Zahratusita Sumitra', role: 'Sekretaris 2', quote: 'Wewangian bunga merebak seiring kebaikan yang dibagikan.' }
];

export const staticMemories = [
  { title: "Masa Orientasi", date: "Agustus 2025", desc: "Hari pertama berkumpul sebagai kesatuan XII IPA 5.", rotate: "-2deg", bg: "linear-gradient(135deg, #5C1414 0%, #8B3333 100%)", order: 1 },
  { title: "Persiapan Ujian", date: "Oktober 2025", desc: "Kegiatan belajar bersama menjelang Evaluasi Tengah Semester.", rotate: "1.5deg", bg: "linear-gradient(160deg, #3A0A0A 0%, #6B2020 60%)", order: 2 },
  { title: "Partisipasi PORSENI", date: "November 2025", desc: "Menjalin sportivitas dan kreativitas kelas.", rotate: "-1deg", bg: "linear-gradient(145deg, #C4973A 0%, #8B6020 50%, #5C1414 100%)", order: 3 },
  { title: "Solidaritas Harian", date: "Sepanjang Tahun", desc: "Interaksi edukatif dan kolaboratif antar siswa sehari-hari.", rotate: "2deg", bg: "linear-gradient(125deg, #4A0E0E 30%, #7A3535 100%)", order: 4 },
  { title: "Tutup Tahun Akademik", date: "2025–2026", desc: "Catatan penutup satu siklus studi.", rotate: "-1.5deg", bg: "linear-gradient(170deg, #5C1414 0%, #C4973A 100%)", order: 5 }
];
